/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/food/Cannon.tsx public/models/cannon-mobile/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { animated, SpringValue } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    cannonMobile_8angles_1: THREE.Mesh;
    cannonMobile_8angles_2: THREE.Mesh;
    barrel_2: THREE.Mesh;
    wheel_backLeft_1: THREE.Mesh;
    wheel_backLeft_2: THREE.Mesh;
  };
  materials: {
    ["iron.003"]: THREE.MeshStandardMaterial;
    ["wood.006"]: THREE.MeshStandardMaterial;
  };
};

export function Cannon(props: JSX.IntrinsicElements["group"] & { cannonScale: SpringValue<number> }) {
  const { nodes, materials } = useGLTF("/models/cannon-mobile/model.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.122, 0, -7.725]}>
        <mesh geometry={nodes.cannonMobile_8angles_1.geometry} material={materials["iron.003"]} />
        <mesh geometry={nodes.cannonMobile_8angles_2.geometry} material={materials["wood.006"]} />
        <animated.mesh geometry={nodes.barrel_2.geometry} scale={props.cannonScale} material={materials["iron.003"]} position={[0, 0.45, -0.067]} />
        <group position={[-0.217, 0.128, 0.262]}>
          <mesh geometry={nodes.wheel_backLeft_1.geometry} material={materials["iron.003"]} />
          <mesh geometry={nodes.wheel_backLeft_2.geometry} material={materials["wood.006"]} />
        </group>
        <group position={[0.217, 0.128, 0.262]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.wheel_backLeft_1.geometry} material={materials["iron.003"]} />
          <mesh geometry={nodes.wheel_backLeft_2.geometry} material={materials["wood.006"]} />
        </group>
        <group position={[-0.217, 0.128, -0.197]}>
          <mesh geometry={nodes.wheel_backLeft_1.geometry} material={materials["iron.003"]} />
          <mesh geometry={nodes.wheel_backLeft_2.geometry} material={materials["wood.006"]} />
        </group>
        <group position={[0.217, 0.128, -0.197]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.wheel_backLeft_1.geometry} material={materials["iron.003"]} />
          <mesh geometry={nodes.wheel_backLeft_2.geometry} material={materials["wood.006"]} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/cannon-mobile/model.gltf");
