/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/food/Ketchup.tsx public/models/bottle-ketchup/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { animated } from "@react-spring/three";
type GLTFResult = GLTF & {
  nodes: {
    bottleKetchup: THREE.Mesh;
  };
  materials: {
    red: THREE.MeshStandardMaterial;
  };
};

export function Ketchup(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/bottle-ketchup/model.gltf") as unknown as GLTFResult;
  return (
    <animated.group {...props} dispose={null}>
      <mesh geometry={nodes.bottleKetchup.geometry} material={materials.red} scale={0.208} position={[-0.5, -0.2, 0]} />
    </animated.group>
  );
}

useGLTF.preload("/models/bottle-ketchup/model.gltf");
