/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/food/Musterd.tsx public/models/bottle-musterd/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { animated } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    bottleMusterd: THREE.Mesh;
  };
  materials: {
    yellow: THREE.MeshStandardMaterial;
  };
};

export function Musterd(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/bottle-musterd/model.gltf") as unknown as GLTFResult;
  return (
    <animated.group {...props} dispose={null}>
      <mesh geometry={nodes.bottleMusterd.geometry} material={materials.yellow} scale={0.21} position={[0.5, -0.2, 0]} />
    </animated.group>
  );
}

useGLTF.preload("/models/bottle-musterd/model.gltf");
