/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/food/TargetStand.tsx public/models/target-stand/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { animated } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder016: THREE.Mesh;
    Cylinder016_1: THREE.Mesh;
    Cylinder016_2: THREE.Mesh;
  };
  materials: {
    ["Red.025"]: THREE.MeshStandardMaterial;
    ["White.025"]: THREE.MeshStandardMaterial;
    ["BrownDark.018"]: THREE.MeshStandardMaterial;
  };
};

export function TargetStand(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/target-stand/model.gltf") as unknown as GLTFResult;

  return (
    <animated.group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder016.geometry} material={materials["Red.025"]} />
        <mesh geometry={nodes.Cylinder016_1.geometry} material={materials["White.025"]} />
        <mesh geometry={nodes.Cylinder016_2.geometry} material={materials["BrownDark.018"]} />
      </group>
    </animated.group>
  );
}

useGLTF.preload("/models/target-stand/model.gltf");
