/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/horror/Bookcase.tsx public/models/bookcase-wide/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useSpring, animated } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    Cube033: THREE.Mesh;
    Cube033_1: THREE.Mesh;
    Cube033_2: THREE.Mesh;
    Cube033_3: THREE.Mesh;
    Cube033_4: THREE.Mesh;
    Cube033_5: THREE.Mesh;
    Cube033_6: THREE.Mesh;
    Cube033_7: THREE.Mesh;
    Cube033_8: THREE.Mesh;
  };
  materials: {
    ["BrownDark.049"]: THREE.MeshStandardMaterial;
    ["PurpleDark.003"]: THREE.MeshStandardMaterial;
    ["White.034"]: THREE.MeshStandardMaterial;
    ["Metal.080"]: THREE.MeshStandardMaterial;
    ["BlueDark.003"]: THREE.MeshStandardMaterial;
    ["GreenDark.007"]: THREE.MeshStandardMaterial;
    ["WoodDark.005"]: THREE.MeshStandardMaterial;
    ["StoneDark.001"]: THREE.MeshStandardMaterial;
    ["Black.030"]: THREE.MeshStandardMaterial;
  };
};

export function Bookcase(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/bookcase-wide/model.gltf") as unknown as GLTFResult;
  const { bookcaseY, booksScale } = useSpring({
    from: {
      bookcaseY: -2.2,
      booksScale: 0,
      caseTilt: Math.PI / 2,
    },
    to: [
      {
        bookcaseY: 0,
        booksScale: 1,
      },

      {
        caseTilt: Math.PI,

        bookcaseY: -2.2,
        booksScale: 0,
      },
    ],
    config: {
      mass: 5,
      tension: 400,
      friction: 40,
    },
    loop: true,
  });

  return (
    <group {...props} dispose={null}>
      <animated.group rotation-x={Math.PI / 2} position-y={bookcaseY}>
        <mesh geometry={nodes.Cube033.geometry} material={materials["BrownDark.049"]} />
        <animated.group scale={booksScale}>
          <mesh geometry={nodes.Cube033_1.geometry} material={materials["PurpleDark.003"]} />
          <mesh geometry={nodes.Cube033_2.geometry} material={materials["White.034"]} />
          <mesh geometry={nodes.Cube033_3.geometry} material={materials["Metal.080"]} />
          <mesh geometry={nodes.Cube033_4.geometry} material={materials["BlueDark.003"]} />
          <mesh geometry={nodes.Cube033_5.geometry} material={materials["GreenDark.007"]} />
          <mesh geometry={nodes.Cube033_6.geometry} material={materials["WoodDark.005"]} />
          <mesh geometry={nodes.Cube033_7.geometry} material={materials["StoneDark.001"]} />
          <mesh geometry={nodes.Cube033_8.geometry} material={materials["Black.030"]} />
        </animated.group>
      </animated.group>
    </group>
  );
}

useGLTF.preload("/models/bookcase-wide/model.gltf");
