/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/horror/Cauldron.tsx public/models/cauldron/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { Sparkles, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Sphere015: THREE.Mesh;
    Sphere015_1: THREE.Mesh;
    Sphere015_2: THREE.Mesh;
    Sphere015_3: THREE.Mesh;
  };
  materials: {
    ["Black.005"]: THREE.MeshStandardMaterial;
    GreenLight: THREE.MeshStandardMaterial;
    Green: THREE.MeshStandardMaterial;
    BrownDark: THREE.MeshStandardMaterial;
  };
};

export function Cauldron(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/cauldron/model.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere015.geometry} material={materials["Black.005"]} />
      <mesh geometry={nodes.Sphere015_1.geometry} material={materials.GreenLight}>
        <Sparkles count={64} scale={2} size={40} speed={0.4} color={"#77FF77"} position={[0, 0.5, 0]} />
      </mesh>
      <mesh geometry={nodes.Sphere015_2.geometry} material={materials.Green} />
      <mesh geometry={nodes.Sphere015_3.geometry} material={materials.BrownDark} />
    </group>
  );
}

useGLTF.preload("/models/cauldron/model.gltf");
