/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/horror/Fence.tsx public/models/fence/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder095: THREE.Mesh;
    Cylinder095_1: THREE.Mesh;
  };
  materials: {
    ["Black.011"]: THREE.MeshStandardMaterial;
    ["Stone.003"]: THREE.MeshStandardMaterial;
  };
};

export function Fence(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/fence/model.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder095.geometry} material={materials["Black.011"]} />
      <mesh geometry={nodes.Cylinder095_1.geometry} material={materials["Stone.003"]} />
    </group>
  );
}

useGLTF.preload("/models/fence/model.gltf");
