/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/horror/Witch.tsx public/models/witch/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube020: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube020_2: THREE.Mesh;
    Cube020_3: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube018_1: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube019_1: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube017_1: THREE.Mesh;
    Cube017_2: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    Cube016_2: THREE.Mesh;
  };
  materials: {
    ["Purple.008"]: THREE.MeshStandardMaterial;
    ["Black.019"]: THREE.MeshStandardMaterial;
    ["Yellow.010"]: THREE.MeshStandardMaterial;
    ["GreenLight.003"]: THREE.MeshStandardMaterial;
    ["Green.003"]: THREE.MeshStandardMaterial;
  };
};

export function Witch(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/witch/model.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube020.geometry} material={materials["Purple.008"]} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials["Black.019"]} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials["Yellow.010"]} />
        <mesh geometry={nodes.Cube020_3.geometry} material={materials["GreenLight.003"]} />
        <group position={[0.204, 0, -0.634]}>
          <mesh geometry={nodes.Cube018.geometry} material={materials["GreenLight.003"]} />
          <mesh geometry={nodes.Cube018_1.geometry} material={materials["Purple.008"]} />
        </group>
        <group position={[-0.204, 0, -0.634]}>
          <mesh geometry={nodes.Cube019.geometry} material={materials["Purple.008"]} />
          <mesh geometry={nodes.Cube019_1.geometry} material={materials["GreenLight.003"]} />
        </group>
        <group position={[0, 0, -0.704]}>
          <mesh geometry={nodes.Cube017.geometry} material={materials["Black.019"]} />
          <mesh geometry={nodes.Cube017_1.geometry} material={materials["GreenLight.003"]} />
          <mesh geometry={nodes.Cube017_2.geometry} material={materials["Green.003"]} />
          <group position={[0, -0.071, -0.768]} rotation={[-0.264, 0, 0]}>
            <mesh geometry={nodes.Cube016.geometry} material={materials["Purple.008"]} />
            <mesh geometry={nodes.Cube016_1.geometry} material={materials["Black.019"]} />
            <mesh geometry={nodes.Cube016_2.geometry} material={materials["Yellow.010"]} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/witch/model.gltf");
