/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t public/models/palm-detailed-long/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Group_152: THREE.Mesh;
    Group_154: THREE.Mesh;
  };
  materials: {
    ["wood.011"]: THREE.MeshStandardMaterial;
    ["leaves.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/palm-detailed-long/model.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[3.923, 0, -7.168]}>
        <mesh geometry={nodes.Group_152.geometry} material={materials["wood.011"]} position={[-0.645, 0, 0.589]} scale={0.766} />
        <mesh geometry={nodes.Group_154.geometry} material={materials["leaves.001"]} position={[0, 1.725, 0]} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/palm-detailed-long/model.gltf");
