/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/park/FerrisWheel.tsx public/models/ferris-wheel/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["ferris_wheel-Mesh"]: THREE.Mesh;
    ["ferris_wheel-Mesh_1"]: THREE.Mesh;
    ["ferris_wheel-Mesh_2"]: THREE.Mesh;
    ["ferris_wheel-Mesh_3"]: THREE.Mesh;
    ["ferris_wheel-Mesh_4"]: THREE.Mesh;
    ["ferris_wheel-Mesh_5"]: THREE.Mesh;
    ["ferris_wheel-Mesh_6"]: THREE.Mesh;
    ["ferris_wheel-Mesh_7"]: THREE.Mesh;
    ["ferris_wheel-Mesh_8"]: THREE.Mesh;
    ["ferris_wheel-Mesh_9"]: THREE.Mesh;
  };
  materials: {
    _cabin_green: THREE.MeshStandardMaterial;
    ferris_wheel_white: THREE.MeshStandardMaterial;
    ferris_wheel_red: THREE.MeshStandardMaterial;
    ferris_wheel_yellow: THREE.MeshStandardMaterial;
    ferris_wheel_legs_red: THREE.MeshStandardMaterial;
    ferris_wheel_blue: THREE.MeshStandardMaterial;
    ferris_wheel_orange: THREE.MeshStandardMaterial;
    cabin_red: THREE.MeshStandardMaterial;
    cabin_blue: THREE.MeshStandardMaterial;
    cabin_orange: THREE.MeshStandardMaterial;
  };
};

export function FerrisWheel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/ferris-wheel/model.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["ferris_wheel-Mesh"].geometry} material={materials._cabin_green} />
      <mesh geometry={nodes["ferris_wheel-Mesh_1"].geometry} material={materials.ferris_wheel_white} />
      <mesh geometry={nodes["ferris_wheel-Mesh_2"].geometry} material={materials.ferris_wheel_red} />
      <mesh geometry={nodes["ferris_wheel-Mesh_3"].geometry} material={materials.ferris_wheel_yellow} />
      <mesh geometry={nodes["ferris_wheel-Mesh_4"].geometry} material={materials.ferris_wheel_legs_red} />
      <mesh geometry={nodes["ferris_wheel-Mesh_5"].geometry} material={materials.ferris_wheel_blue} />
      <mesh geometry={nodes["ferris_wheel-Mesh_6"].geometry} material={materials.ferris_wheel_orange} />
      <mesh geometry={nodes["ferris_wheel-Mesh_7"].geometry} material={materials.cabin_red} />
      <mesh geometry={nodes["ferris_wheel-Mesh_8"].geometry} material={materials.cabin_blue} />
      <mesh geometry={nodes["ferris_wheel-Mesh_9"].geometry} material={materials.cabin_orange} />
    </group>
  );
}

useGLTF.preload("/models/ferris-wheel/model.gltf");
