/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t -o src/components/park/Ship.tsx public/models/ship-light/model.gltf 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ship_light_8angles_1: THREE.Mesh;
    ship_light_8angles_2: THREE.Mesh;
    ship_light_8angles_3: THREE.Mesh;
    ship_light_8angles_4: THREE.Mesh;
    ship_light_8angles_5: THREE.Mesh;
    ship_light_8angles_6: THREE.Mesh;
    cannon_front_1_1: THREE.Mesh;
    cannon_front_1_2: THREE.Mesh;
    cannon_front_1001: THREE.Mesh;
    cannon_left_1_1: THREE.Mesh;
    cannon_left_1_2: THREE.Mesh;
    cannon_left_1001: THREE.Mesh;
    cannon_left_1001_1: THREE.Mesh;
    cannon_left_1001_2: THREE.Mesh;
    cannon_right_1001: THREE.Mesh;
    sail_back_1_1: THREE.Mesh;
    sail_back_1_2: THREE.Mesh;
    sail_front_1_1: THREE.Mesh;
    sail_front_1_2: THREE.Mesh;
    sail_middle_1_1: THREE.Mesh;
    sail_middle_1_2: THREE.Mesh;
    steering_1_1: THREE.Mesh;
    steering_1_2: THREE.Mesh;
  };
  materials: {
    ["wood.019"]: THREE.MeshStandardMaterial;
    ["woodDark.001"]: THREE.MeshStandardMaterial;
    ["iron.009"]: THREE.MeshStandardMaterial;
    ["window.001"]: THREE.MeshStandardMaterial;
    ["textile.005"]: THREE.MeshStandardMaterial;
    ["_defaultMat.003"]: THREE.MeshStandardMaterial;
  };
};

export function Ship(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/ship-light/model.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.715, 0, 0.014]}>
        <mesh geometry={nodes.ship_light_8angles_1.geometry} material={materials["wood.019"]} />
        <mesh geometry={nodes.ship_light_8angles_2.geometry} material={materials["woodDark.001"]} />
        <mesh geometry={nodes.ship_light_8angles_3.geometry} material={materials["iron.009"]} />
        <mesh geometry={nodes.ship_light_8angles_4.geometry} material={materials["window.001"]} />
        <mesh geometry={nodes.ship_light_8angles_5.geometry} material={materials["textile.005"]} />
        <mesh geometry={nodes.ship_light_8angles_6.geometry} material={materials["_defaultMat.003"]} />
        <group position={[0, 1.437, -3.616]}>
          <mesh geometry={nodes.cannon_front_1_1.geometry} material={materials["iron.009"]} />
          <mesh geometry={nodes.cannon_front_1_2.geometry} material={materials["wood.019"]} />
          <mesh geometry={nodes.cannon_front_1001.geometry} material={materials["iron.009"]} position={[0, 0.278, -0.067]} rotation={[0.073, 0, 0]} />
        </group>
        <group position={[-0.76, 1.277, -1.681]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes.cannon_left_1_1.geometry} material={materials["iron.009"]} />
          <mesh geometry={nodes.cannon_left_1_2.geometry} material={materials["wood.019"]} />
          <mesh geometry={nodes.cannon_left_1001.geometry} material={materials["iron.009"]} position={[0, 0.444, -0.067]} rotation={[0.093, 0, 0]} />
          <group position={[-0.217, 0.128, 0.262]}>
            <mesh geometry={nodes.cannon_left_1001_1.geometry} material={materials["iron.009"]} />
            <mesh geometry={nodes.cannon_left_1001_2.geometry} material={materials["wood.019"]} />
          </group>
          <group position={[0.217, 0.128, 0.262]} rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.cannon_left_1001_1.geometry} material={materials["iron.009"]} />
            <mesh geometry={nodes.cannon_left_1001_2.geometry} material={materials["wood.019"]} />
          </group>
          <group position={[-0.217, 0.128, -0.197]}>
            <mesh geometry={nodes.cannon_left_1001_1.geometry} material={materials["iron.009"]} />
            <mesh geometry={nodes.cannon_left_1001_2.geometry} material={materials["wood.019"]} />
          </group>
          <group position={[0.217, 0.128, -0.197]} rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.cannon_left_1001_1.geometry} material={materials["iron.009"]} />
            <mesh geometry={nodes.cannon_left_1001_2.geometry} material={materials["wood.019"]} />
          </group>
        </group>
        <group position={[0.76, 1.277, -1.681]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.cannon_left_1_1.geometry} material={materials["iron.009"]} />
          <mesh geometry={nodes.cannon_left_1_2.geometry} material={materials["wood.019"]} />
          <mesh geometry={nodes.cannon_right_1001.geometry} material={materials["iron.009"]} position={[0, 0.444, -0.067]} rotation={[0.093, 0, 0]} />
          <group position={[-0.217, 0.128, 0.262]}>
            <mesh geometry={nodes.cannon_left_1001_1.geometry} material={materials["iron.009"]} />
            <mesh geometry={nodes.cannon_left_1001_2.geometry} material={materials["wood.019"]} />
          </group>
          <group position={[0.217, 0.128, 0.262]} rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.cannon_left_1001_1.geometry} material={materials["iron.009"]} />
            <mesh geometry={nodes.cannon_left_1001_2.geometry} material={materials["wood.019"]} />
          </group>
          <group position={[-0.217, 0.128, -0.197]}>
            <mesh geometry={nodes.cannon_left_1001_1.geometry} material={materials["iron.009"]} />
            <mesh geometry={nodes.cannon_left_1001_2.geometry} material={materials["wood.019"]} />
          </group>
          <group position={[0.217, 0.128, -0.197]} rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.cannon_left_1001_1.geometry} material={materials["iron.009"]} />
            <mesh geometry={nodes.cannon_left_1001_2.geometry} material={materials["wood.019"]} />
          </group>
        </group>
        <group position={[1.354, 3.034, 1.864]}>
          <mesh geometry={nodes.sail_back_1_1.geometry} material={materials["textile.005"]} />
          <mesh geometry={nodes.sail_back_1_2.geometry} material={materials["wood.019"]} />
        </group>
        <group position={[1.354, 1.604, -3.201]}>
          <mesh geometry={nodes.sail_front_1_1.geometry} material={materials["textile.005"]} />
          <mesh geometry={nodes.sail_front_1_2.geometry} material={materials["wood.019"]} />
        </group>
        <group position={[1.354, 1.604, -1.546]}>
          <mesh geometry={nodes.sail_middle_1_1.geometry} material={materials["textile.005"]} />
          <mesh geometry={nodes.sail_middle_1_2.geometry} material={materials["wood.019"]} />
        </group>
        <group position={[0, 2.776, 1.051]}>
          <mesh geometry={nodes.steering_1_1.geometry} material={materials["wood.019"]} />
          <mesh geometry={nodes.steering_1_2.geometry} material={materials["iron.009"]} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/ship-light/model.gltf");
